02_AdvancedSageMaker: streamlined setup of bindings between R and Python and amended Dockerfile-training container
aws-samples/rstudio-on-sagemaker-workshop pull request #12
Opened 2023-04-07 15:44 UTC by bishrtabbaa

1. Streamlined setup of correct bindings between R and Python due to … numpy and BLAS dependencies.  2. Fixed Dockerfile for training job to install python3-boto3 via apt-get.

*Issue #11 :*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-04-10 17:29 UTC, seanpmorgan requested changes

2023-04-10 17:29 UTC, seanpmorgan commented on 02_AdvancedSageMaker/01_SageMakerProcessing.Rmd
> +
Can we make this a {bash} cell so that the user can just run the Rmd file without error?

2023-04-11 01:53 UTC, bishrtabbaa commented on 02_AdvancedSageMaker/01_SageMakerProcessing.Rmd
> +
Yep.  Done.  Let me know what you think.

2023-04-14 21:06 UTC, seanpmorgan approved these changes
LGTM tyvm

2023-04-14 21:06 UTC, merged